### ISSUE TITLE
whisper-rs-sys published to crates.io is out-of-date

### ISSUE THREAD

**Issue by jac3km4** [tazz4843/whisper-rs#29]
Hi,
I've been trying to use this as a dependency on Windows (MSVC), but it appears that the latest version of the `sys` crate published to crates.io is out-of-date and doesn't build.
The `master` branch of this repository contains a fix (6f03b925cca4aea83e292a5870e7e3363e13877a), which appears to work, but it hasn't been published ([latest version in crates.io](https://crates.io/crates/whisper-rs-sys/versions) is older than the commit).

As a workaround it's possible to use this as a git dependency:
```toml
[dependencies.whisper-rs]
git = "https://github.com/tazz4843/whisper-rs"
```
